services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: elderco
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynetwork

  web:
    build:
      context: ..
      dockerfile: Dockerfile
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ..:/app
      - ./wait-for-it.sh:/wait-for-it.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  db_data:
